@baseUrl = http://localhost:5009
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5NDAxMDliNi1iZGM1LTQ3Y2MtOTQyYi1jNDUzNzA5NjZlMGMiLCJlbWFpbCI6ImFkbWluQGtpbmRlcmh1Yi5jb20iLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3ODA1MTA2NDgsImV4cCI6MTc4MDUxNDI0OCwiaWF0IjoxNzgwNTEwNjQ4LCJpc3MiOiJLaW5kZXJIdWIuSWRlbnRpdHkiLCJhdWQiOiJLaW5kZXJIdWIifQ.njx3FhJR4pW1H2fGhARssTroKR1hyD_uRTx4jmpLGPg
@teacherToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkOGMzY2U2Ni1mMjUyLTQ5MTEtODBhNS0yOWM0NGQzY2EzMzUiLCJlbWFpbCI6ImphbmUyQGtpbmRlcmh1Yi5jb20iLCJyb2xlIjoiVGVhY2hlciIsIm5iZiI6MTc4MDUxMDc0NywiZXhwIjoxNzgwNTE0MzQ3LCJpYXQiOjE3ODA1MTA3NDcsImlzcyI6IktpbmRlckh1Yi5JZGVudGl0eSIsImF1ZCI6IktpbmRlckh1YiJ9.RTj3B1DZB_FBZ5SxQsYkfdmnOk57ij4fxijNmzJjM2g
@classroomId = 766d1638-40a3-4b81-84df-a16218c83404
@teacherUserId = d8c3ce66-f252-4911-80a5-29c44d3ca335

### Create classroom
POST {{baseUrl}}/api/classrooms
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Sunflower Room",
  "ageGroup": 0
}

### Assign teacher - happy path
POST {{baseUrl}}/api/classrooms/{{classroomId}}/teachers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "teacherId": "{{teacherUserId}}"
}

### Assign same teacher again - expect 409
POST {{baseUrl}}/api/classrooms/{{classroomId}}/teachers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "teacherId": "{{teacherUserId}}"
}

### Assign teacher to another classroom - expect 409
POST {{baseUrl}}/api/classrooms/{{classroomId}}/teachers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "teacherId": "{{teacherUserId}}"
}

### Get teachers in classroom
GET {{baseUrl}}/api/classrooms/{{classroomId}}/teachers
Authorization: Bearer {{adminToken}}

### Get classroom by ID - verify maxCapacity updated
GET {{baseUrl}}/api/classrooms/{{classroomId}}
Authorization: Bearer {{adminToken}}

### Assign teacher to non-existent classroom - expect 404
POST {{baseUrl}}/api/classrooms/00000000-0000-0000-0000-000000000001/teachers
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "teacherId": "{{teacherUserId}}"
}

### Unassign teacher
DELETE {{baseUrl}}/api/classrooms/{{classroomId}}/teachers/{{teacherUserId}}
Authorization: Bearer {{adminToken}}

### Get classroom after unassign - verify maxCapacity back to 0
GET {{baseUrl}}/api/classrooms/{{classroomId}}
Authorization: Bearer {{adminToken}}