// <auto-generated />
using System;
using KinderHub.Enrollment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KinderHub.Enrollment.Migrations
{
    [DbContext(typeof(EnrollmentDbContext))]
    partial class EnrollmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KinderHub.Enrollment.Models.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsPottyTrained")
                        .HasColumnType("boolean")
                        .HasColumnName("is_potty_trained");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("ix_children_classroom_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_children_parent_id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("integer")
                        .HasColumnName("age_group");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_classrooms");

                    b.ToTable("classrooms", (string)null);
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.ClassroomTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_classroom_teachers");

                    b.HasIndex("ClassroomId", "TeacherId")
                        .IsUnique()
                        .HasDatabaseName("ix_classroom_teachers_classroom_id_teacher_id");

                    b.ToTable("classroom_teachers", (string)null);
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.Waitlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("integer")
                        .HasColumnName("age_group");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_waitlists");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_waitlists_child_id");

                    b.HasIndex("AgeGroup", "Status", "RequestedDate")
                        .HasDatabaseName("ix_waitlists_age_group_status_requested_date");

                    b.ToTable("waitlists", (string)null);
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.Child", b =>
                {
                    b.HasOne("KinderHub.Enrollment.Models.Classroom", "Classroom")
                        .WithMany("Children")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_children_classrooms_classroom_id");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.ClassroomTeacher", b =>
                {
                    b.HasOne("KinderHub.Enrollment.Models.Classroom", "Classroom")
                        .WithMany("ClassroomTeachers")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classroom_teachers_classrooms_classroom_id");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.Waitlist", b =>
                {
                    b.HasOne("KinderHub.Enrollment.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_waitlists_children_child_id");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("KinderHub.Enrollment.Models.Classroom", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ClassroomTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
