@baseUrl = http://localhost:5006

### Register - happy path
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Jo",
  "lastName": "Smith",
  "email": "notavalidemail",
  "phoneNumber": "555-987-6543",
  "password": "weak",
  "role": 2
}